apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api-afip
  namespace: api-afip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-afip
  template:
    metadata:
      labels:
        app: api-afip
    spec:
      containers:
      - name: api-afip
        image: registry.ng.bluemix.net/api-afip/afip_api:1.0
        args:
          - "LICENSE=accept" 
            "NODENAME=MYNODE"
            "SERVERNAME=MYSERVER"
        resources: 
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 125Mi
        ports:
        - name: http
          containerPort: 7872
        lifecycle:
          postStart:
            exec:
              command:
                - "echo"
                - "hola que tal"
      imagePullSecrets:
        - name: api-afip
