kind: Service
metadata:
  name: api-afip
  namespace: api-afip
  labels:
    app: api-afip
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 7872
    targetPort: http
    protocol: TCP
  selector:
    app: api-afip
